### ISSUE TITLE
Installation ~/.rbenv/plugins & Homebrew

### ISSUE THREAD

**Issue by mrjcleaver** [docwhat/rbenv-chefdk#1]
Interesting! I didn't know rbenv did plugins. https://github.com/sstephenson/rbenv/issues/691

Some points about instructions:

> This is usually ~/.rbenv/plugins or /usr/local/var/rbenv/plugins if you use Homebrew on OS X.

I don't know why, but even though I do use Homebrew on OS X, it looks like this is ~/.rbenv/plugins for me.

Further, I had to make this ~/.rbenv/plugins - it would be nice to be able to `brew install rbenv-chefdk` instead of this:

```
martincleaver@martincaversmbp:~ 09:34:07 508$ cd .rbenv/
martincleaver@martincaversmbp:~/.rbenv 09:37:35 509$ ls
shims    version  versions
martincleaver@martincaversmbp:~/.rbenv 09:37:35 510$ mkdir plugins
martincleaver@martincaversmbp:~/.rbenv 09:37:38 511$ cd plugins/
martincleaver@martincaversmbp:~/.rbenv/plugins 09:37:40 512$ ls
martincleaver@martincaversmbp:~/.rbenv/plugins 09:37:40 513$ git clone https://github.com/docwhat/rbenv-chefdk.git
Cloning into 'rbenv-chefdk'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 22 (delta 2), reused 20 (delta 0)
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
martincleaver@martincaversmbp:~/.rbenv/plugins 09:38:47 514$ ls
rbenv-chefdk
```

Not least because this could be clearer:

> Then symlink your ChefDK embedded directory into your $RBENV_ROOT/versions directory. For example:
> mkdir "$RBENV_ROOT/versions/chefdk"

So, mkdir a symlink does not make... did you mean something like:

```
martincleaver@martincaversmbp:~/.rbenv/versions 09:23:41 850$ ls -la
total 8
drwxr-xr-x  5 martincleaver  staff  170  1 Dec 15:16 .
drwxr-xr-x  5 martincleaver  staff  170  6 Nov 01:59 ..
drwxr-xr-x  6 martincleaver  staff  204  6 Nov 01:56 1.9.3-p125
drwxr-xr-x  6 martincleaver  staff  204  1 Dec 15:16 1.9.3-p327
lrwxr-xr-x  1 martincleaver  staff   20  6 Nov 02:11 chefdk -> /opt/chefdk/embedded
```

i.e.

```
martincleaver@martincaversmbp:~/.rbenv/versions 09:48:55 865$ ln -s /opt/chefdk/embedded chefdk
```

**Comment by mrjcleaver** [comment]
Finally it would be useful to have instruction of what to test.

Judging by https://github.com/docwhat/rbenv-chefdk/blob/master/etc/rbenv.d/which/rbenv-chefdk.bash#L7 I'm supposing:

```
martincleaver@martincaversmbp:~ 09:51:32 501$ rbenv which ruby
/Volumes/Storage/martincleaver/.rbenv/versions/chefdk/bin/ruby
```

But a real test comparing to expected output would help.

Thanks a lot, M.

**Comment by mrjcleaver** [comment]
And do I need to do:

```
rbenv rehash
```

?

**Comment by docwhat** [comment]
whooo... lots of things...

Alright... let me go through them.
1. I'll fix the instructions re: `$RBENV_ROOT`.  It is suggested, but not enforced, to use `/usr/local/var/rbenv`.
2. Symlink vs. Directory.  My first attempt required a symlink, but it now requires just an empty directory.  This is because the `/opt/chefdk/embedded/bin` directory contains commands that can break your system, especially if shims are created.  See chef/chef-dk#313 for more info.
3. Yeah, doing `rbenv rehash` is a good idea. 
4. `rbenv which ruby` should show "/opt/chefdk/embedded/bin/ruby".

I've pushed some changes to the README up.  If they are confusing then tell me and I'll try to adjust them.

**Comment by docwhat** [comment]
PS: sorry I missed you on IRC... I'm usually there during business hours and at random times on weekends.

**Comment by mrjcleaver** [comment]
Thanks @docwhat - I just came back to install on my Mac Mini. Better experience this time.

One thing:

```
To install rbenv-chefdk, clone this repository into the $RBENV_ROOT/plugins directory. This is usually ~/.rbenv/plugins or /usr/local/var/rbenv/plugins if you follow the suggestion in Homebrew on OS X.
```

Would be better written out:

To install rbenv-chefdk, clone this repository into the $RBENV_ROOT/plugins directory. 

```
cd $RBENV_ROOT/plugins
git clone <url> 
```

This is usually ~/.rbenv/plugins or /usr/local/var/rbenv/plugins if you follow the suggestion in Homebrew on OS X.

Simply because I misread the condensed paragraph and forgot "plugins"

Cheers, M.

**Comment by docwhat** [comment]
@mrjcleaver Would you be willing to put that into a pull request?  You can edit the README directly via GitHub to create a fork and pull request automagically.

**Comment by mrjcleaver** [comment]
Here you go!
