### ISSUE TITLE
add support for chef-dk versions (ensure team uses same version)

### ISSUE THREAD

**Issue by neurogenesis** [docwhat/rbenv-chefdk#11]
One of the biggest problems that ChefDK sought to solve was the dependency nightmare with the various components used from development through test to deployment into production.

The downside is that solving that problem meant you can no longer rely on a Gemfile and Gemfile.lock to ensure an entire team is using the same version of the tools used to test code (including CI tools which use test-kitchen). It should be obvious to anyone who builds and deploys software to production that not having reproducible builds and tests is a problem. For example, we've seen cookbooks that once passed test-kitchen suddenly fail because it was dynamically pulling in the latest version of tools like busser. So a project may pass for one member of the team and not another if they're on different versions of ChefDK.

To restore the ability to lock members of a team into using the same chef ecosystem, it would be great if rbenv-chefdk could support something like this:

a .ruby-version file in a cookbook's parent directly would contain chefdk-1.5, chefdk-1.6, etc.

if a user has a different version of chef-dk installed than the one specified in .ruby-version, an error will be thrown.

**Comment by civik** [comment]
So i've actually been exploring this topic a bit.  Ideally you could distribute a config that would ensure parity in a users chefDK / Ruby env to ensure compatibility for team coding. I'm working on actually doing an automated ChefDK build in a rbenv.  I'll let you know if I publish anything.

**Comment by docwhat** [comment]
Isn't getting everyone to use the same ChefDK version and the same chef-client version the best way to deal with this?

To get `rbenv` to understand `chefdk-<version>` would probably require using `rbenv` to install ChefDK itself.  By default, ChefDK installs to `/opt/chefdk`.

**Comment by docwhat** [comment]
I've forked this into [rbenv-chef-workstation](https://github.com/docwhat/rbenv-chef-workstation).

If you're still interested, feel free to open something there.
