### ISSUE TITLE
rbenv-chefdk appears to be incompatible with rbenv-bundle-exec

### ISSUE THREAD

**Issue by jared** [docwhat/rbenv-chefdk#12]
With both plugins installed to `~/.rbenv/plugins`, attempts to execute chef-specific commands with the embedded ruby results in the following error:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:355:in 'block in replace_bin_path': can't find executable chef (Gem::Exception) from /opt/chefdk/embedded/bin/chef:22:in
```

This definitely impacts both the `chef` and `berks` executable files, I'm not sure on others.

Removing the `rbenv-bundle-exec` plugin restores the functionality of the chef executables.

**Comment by JonathanSerafini** [comment]
Ran into this as well and had to add a .no_bundle_exec file for rbenv-bundle-exec.

```
echo chef >> ~/.no_bundle_exec
echo berks >> ~/.no_bundle_exec
chef
```

**Comment by docwhat** [comment]
I don't actually use [`rbenv-bundle-exec`](https://github.com/maljub01/rbenv-bundle-exec).  I use `rbenv-binstubs` instead.

I suspect the only way to fix this reliably is by having `rbenv-chefdk` actually install and manage ChefDK in the `$(rbenv root)/versions` directory itself (as in issue #11).

Meanwhile, I'll add a note to the FAQ section of the README.

**Comment by docwhat** [comment]
Does the commit 8d76fb58f5941e81a4487e6674763b51d406f380 I just pushed up help at all?

**Comment by docwhat** [comment]
Closing as there hasn't been any activity in a long time.

Plus [rbenv-chef-workstation](https://github.com/docwhat/rbenv-chef-workstation) is the new ChefDK.
