### ISSUE TITLE
What about GEM_PATH?

### ISSUE THREAD

**Issue by mrjcleaver** [docwhat/rbenv-chefdk#13]
Should GEM_PATH and GEM_ROOT be set?

I'm assuming the recommendation is never to thereafter chef shell-init bash, but that also sets those variables.

BTW: are you at ChefConf this week? I am.

**Comment by docwhat** [comment]
I am not, alas, at ChefConf.  If you're ever in Pittsburgh I'll buy you beer, tho!

I haven't needed to set `GEM_PATH` and `GEM_ROOT`.  To be honest, I don't recall why not anymore. :-/

Example:

```
∓ chef gem install awesome_print
Fetching: awesome_print-1.7.0.gem (100%)
WARNING:  You don't have /Users/docwhat/.chefdk/gem/ruby/2.1.0/bin in your PATH,
          gem executables will not run.
Successfully installed awesome_print-1.7.0
1 gem installed
```

I could get rid of that warning, I guess.  I could modify the `PATH` when the shim for `chef` or `gem` is run.

Do you have problems due to not having `GEM_*` set?

**Comment by mrjcleaver** [comment]
I'm generally a bit perplexed: https://discourse.chef.io/t/multiple-rubies-rbenv-is-painful-chefdk-inside-docker-for-mac/8839 !

**Comment by mrjcleaver** [comment]
Ok, issues turned out partly to be that (@patcon) and I were executing "bundle exec " - and, because this was failing for me (Patrick doesn't use rbenv), I had tried various things, including making it worse by adding /opt/chefdk & embedded/bin directly into the path. That fubar'd my rbenv-chefdk.

Bundle exec was failing because there was a undeclared dependency on rb-readline in the ChefDK. Luckily @jkeiser was at ChefChef2016, was a nice enough to spend time to hack through the issue, and had sufficient Ruby / Bundle smarts to figure it out... he determine a workaround (adding the missing dependency to rb-readline in my chef repo's Gemfile)... this has fixed it in the interim for me.

John - any date on when a revised ChefDK might be out with this in? Also, there maybe a missing dependency on i18n as well.

Thanks guys, Martin.

**Comment by docwhat** [comment]
I just added an `rbenv exec` hook that _does_ run `chef shell-init sh` under the covers, so it will be set now.  This was to help address #3 so others wouldn't have those issues.

**Comment by mrjcleaver** [comment]
Excellent, so glad to have helped!
