### ISSUE TITLE
Provide an ENV checker utility

### ISSUE THREAD

**Issue by mrjcleaver** [docwhat/rbenv-chefdk#14]
So... it turns out that Ruby gets extremely confused if chefdk is in the path both via rbenv and directly, especially if it's invoked via bundle install.

I suspect that a "check I did it right" utility (checkenv.sh or similar) would go a long way to help n00bs from messing up.

I think it needs to check for GEM_PATH, GEM_ROOT, and then the presence of rbenv shims in PATH alongside chefdk anything else that could be checked.

Consider it an anti pattern checker... would have helped with #2 as well.

**Comment by docwhat** [comment]
I added a script and a Troubleshooting section in the README that should fix this.  You can run `$SHELL "$(rbenv root)/plugins/rbenv-chefdk/sanity-check.sh"` to see if it is sane or not.
