### ISSUE TITLE
`chef shell-init` is incompatible with this plugin

### ISSUE THREAD

**Issue by mconigliaro** [docwhat/rbenv-chefdk#2]
It might be worth noting in the docs that running `chef shell-init` [as described in the ChefDK docs](https://docs.chef.io/install_dk.html#set-system-ruby) is incompatible with your plugin. I had set this up earlier and forgot about it, so I was left scratching my head when your plugin wasn't working for me at first.

**Comment by docwhat** [comment]
Added a note via pull request #9 -- 8e83af62050e5b360c63cece9f9f4b953f4fc63a

**Comment by mrjcleaver** [comment]
I was confused by the same. 

I've posted https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/15152973-chefdk-needs-to-be-rbenv-aware
