### ISSUE TITLE
`gem install` and `chef gem install` don't work

### ISSUE THREAD

**Issue by mconigliaro** [docwhat/rbenv-chefdk#3]
After installing this plugin, I can't figure out how to install gems into the ChefDK ruby. I've tried `gem install` and `chef gem install`, but they both result in the same error:

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/chefdk/embedded/lib/ruby/gems/2.1.0 directory.
```

My understanding is that ChefDK's `gem` shouldn't even be trying to install new gems there. It should be using `~/.chefdk` instead.

**Comment by SeanSith** [comment]
Not seeing this issue myself. Can you advise if you're still having this issue?

**Comment by mconigliaro** [comment]
I just tried it again with ChefDK 0.5.1 and I'm getting the same error. Is there anything I should look at to troubleshoot?

**Comment by SeanSith** [comment]
I'd guess you still have the `chef shell-init` line in your profile files (any ChefDK customization needs to be removed if using this plugin) or maybe an older copy of this plugin. Current code doesn't point to anything  that would eventually resolve out to that path.

**Comment by mconigliaro** [comment]
I think part of the problem is that my `RBENV_*` variables are not being set:

```
$ eval "$(rbenv init -)"
$ env | grep RBENV 
$
```

I see that rbenv-chefdk relies on them, but looking at the [rbenv docs](https://github.com/sstephenson/rbenv#environment-variables), it's still not clear to me whether any of these are guaranteed to be set by default.

Edit: Never mind, it looks like those variables actually are being set inside the plugin. They're just not exported.

**Comment by mconigliaro** [comment]
Interestingly, I don't get the gem install error anymore after I run the `chef shell-init` command (presumably because it changes `GEM_HOME`). My recollection was that this broke something else, but I can't remember what...

**Comment by SeanSith** [comment]
It'll break your gem installation process for every one of your other Rubies. It certainly sounds like you've got something odd in your rbenv environment, rather than a problem with this plugin specifically. RBENV_SHELL should be set, at a minimum.

**Comment by mconigliaro** [comment]
For what it's worth, `RBENV_*` is not set in my shell, but I can see them in Ruby:

```
$ ruby -e "puts ENV.select { |k,v| k.start_with?('RBENV') }"
{"RBENV_VERSION"=>"chefdk", "RBENV_ROOT"=>"/Users/mconigliaro/.rbenv", "RBENV_HOOK_PATH"=>":/Users/mconigliaro/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/mconigliaro/.rbenv/plugins/rbenv-chefdk/etc/rbenv.d", "RBENV_DIR"=>"/Users/mconigliaro"}
```

**Comment by mconigliaro** [comment]
I'm still having this problem after reinstalling on three brand new machines:

```
mkdir -p "$(rbenv root)/plugins"
git clone https://github.com/docwhat/rbenv-chefdk.git "$(rbenv root)/plugins/rbenv-chefdk"
mkdir -p "$(rbenv root)/versions/chefdk"
rbenv shell chefdk
rbenv rehash
```

Can someone confirm that after doing this, `gem install` actually installs gems under `~.chefdk`? I can't understand how that works without the `GEM_*` variables that `chef shell-init` is supposed to set.

**Comment by mconigliaro** [comment]
I just tried this again on another new machine, and I get the same error when installing gems. I'm still missing how this plugin gets gems to install to `~/.chefdk` without updating `GEM_PATH`. My workaround right now is to just install gems with `sudo`.

**Comment by docwhat** [comment]
Are you using `chef shell-init` in your shell startup scripts? Because you shouldn't if you're using this plugin.

**Comment by docwhat** [comment]
Also, I apologize for not being more responsive. I have no idea how it happened but I apparently "unwatched" my own repository and wasn't getting notifications.  I didn't even know you could do that!

**Comment by mconigliaro** [comment]
Ha, no problem. Anyway, here's my current [.zprofile](https://github.com/mconigliaro/homefiles/blob/master/.zprofile). I'm running `eval "$(rbenv init -)"` for rbenv, but **not** `eval "$(chef shell-init zsh)"`. Is there something else here that could be messing this up for me?

**Comment by docwhat** [comment]
Does `env | grep -E 'RUBY|GEM'` return anything interesting?

**Comment by mconigliaro** [comment]
It doesn't return anything actually.

```
Mike@ip-192-168-2-99 ~ $ env | grep -E 'RUBY|GEM'
Mike@ip-192-168-2-99 ~ $
```

**Comment by docwhat** [comment]
What's your `PATH`?  Maybe it running the wrong `gem`?

**Comment by mconigliaro** [comment]
```
$ rbenv versions
  system
  2.1.6
  * chefdk (set by /Users/Mike/.rbenv/version)

$ echo $PATH
/Users/Mike/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin

$ which gem
/Users/Mike/.rbenv/shims/gem
```

**Comment by docwhat** [comment]
@mconigliaro -- Okay, this is becoming really hard to troubleshoot via github issue... would you be willing to ScreenHero (a screen sharing application suited for pair programming) on this?

**Comment by mconigliaro** [comment]
Thanks again for the help! `gem install --user-install <gem>` seems like it'll be a better workaround until we figure out what's really going on here.

**Comment by docwhat** [comment]
Hah! I figured it out and was able to recreate it!

The problem is your [`~/.gemrc`](https://github.com/mconigliaro/homefiles/blob/master/.gemrc)...

If you remove/rename that file, then it works!

So what's happening is:
1. ChefDK sets the "default" for `:install` and `:update` to include the `--user` (aka `--user-install`) flag in [operating_system.rb:6](https://github.com/chef/chef-dk/blob/75ecb686077ba901896f0b77194da94c2830cf2e/omnibus/files/rubygems-customization/default/operating_system.rb#L6-L8).
2. Then RubyGems then reads your [`~/.gemrc`](https://github.com/mconigliaro/homefiles/blob/master/.gemrc) file which overrides `:install` and `:update`!

A quick fix is to change your `~/.gemrc` to be:

```
gems: --no-rdoc --no-ri
```

or using the newer syntax:

```
gems: --no-document
```

I could "fix" this, by setting the GEMRC to a custom `.gemrc` file that adds back in the `--user` flag.  But to be honest, that is something that ChefDK should be doing...

I could also fix this by setting the various environment variables that `chef shell-init` sets, which is  roughly what the `--user[-install]` flag is doing anyway.

**Comment by mconigliaro** [comment]
Confirmed working! Thanks again!

**Comment by docwhat** [comment]
I filed a bug with ChefDK: chef/chef-dk#935

I'll see about force-setting the `GEM_` variables. :-/  But that may be tough because I don't use the `shims` mechanism.

**Comment by docwhat** [comment]
@mconigliaro Don't forget to tell your other friends who were having trouble to update the plugin, too.  It should be fixed for them.

**Comment by mconigliaro** [comment]
👍
