### ISSUE TITLE
brew install would be nice

### ISSUE THREAD

**Issue by mrjcleaver** [docwhat/rbenv-chefdk#6]
:)

**Comment by mjuszczak** [comment]
:+1:

**Comment by docwhat** [comment]
I'd be happy to accept a pull request. :)

**Comment by docwhat** [comment]
Actually, you should submit a pull request to homebrew directly. :-)

**Comment by gordonbondon** [comment]
@docwhat hi, I wanted to create a formula, but by homebrew guidelines they need a versioned link. Could you create a github release like described here https://help.github.com/articles/creating-releases/ ?

**Comment by docwhat** [comment]
@gordonbondon: Done!

**Comment by gordonbondon** [comment]
Brew formula is waiting for merge Homebrew/homebrew-core#19990
