### ISSUE TITLE
"	  gem executables will not run."

### ISSUE THREAD

**Issue by mrjcleaver** [docwhat/rbenv-chefdk#7]
Should I still see: WARNING you don't have .chefdk/gem/ruby/2.1.0/bin in your PATH ?

~/.bash_profile

```
rbenv local chefdk
eval "$(rbenv init -)"
#eval "$(chef shell-init bash)"                                                                                              

export PATH="$HOME/bin:$PATH"
```

**Comment by docwhat** [comment]
You can ignore that message; The rbenv shim magic finds those gems and makes them available.

**Comment by docwhat** [comment]
Reopening because I think I can fix this and resolve other issues.
